version: "3.8"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=MY_EMAIL_LETSENCRIPT"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # redirect port 80 -> 443
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    ports:
      - "443:443"
      - "80:80"
      #- "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  guitar-shop-front:
    image: MY_IMAGE
    container_name: "guitar-shop-front"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guitar-shop-front.rule=Host(`MY_HOSTNAME`)"
      - "traefik.http.routers.guitar-shop-front.entrypoints=websecure"
      - "traefik.http.routers.guitar-shop-front.tls.certresolver=myresolver"
      # use compression
      - "traefik.http.routers.guitar-shop-front.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"

