
name: simple

on:
  push:
    branches: [ "main", "develop" ]
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:

  fronttest:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2      
        - name: Setup-node     
          uses: actions/setup-node@v2
          with:
            working-directory: frontend/
            node-version: 16.17
        - name: Install
          working-directory: frontend/
          run: npm ci
        - name: Run Test
          working-directory: frontend/
          run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless                   
      
  frontbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [fronttest]
    steps:
        - name: Checkout
          uses: actions/checkout@v2  
        - name: Setup-node     
          uses: actions/setup-node@v2
          with:
            node-version: 16.17
            working-directory: frontend/
        - name: Install
          working-directory: frontend/
          run: npm ci
        - name: Run build
          working-directory: frontend/
          run: npm run build
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Docker meta
          id: frontmeta
          uses: docker/metadata-action@v5
          with:
            images: ${{ secrets.DOCKERHUB_USERNAME }}/simplecicd
            tags: |
              type=schedule
              type=ref,event=branch
              type=semver,pattern={{version}}
              type=sha
        - name: Build front
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ steps.frontmeta.outputs.tags }}

  frontdeploydev:
    name: deploydev
    runs-on: ubuntu-latest
    needs: [frontbuild]
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
    - uses: actions/checkout@master

  frontdeployprod:
    name: deployprod
    runs-on: ubuntu-latest
    needs: [frontbuild]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@master

